version: "3.7"

services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    depends_on:
      - "pocketbase"
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./reverse-proxy/traefik.yaml:/traefik.yaml"
      - "./reverse-proxy/traefik_dynamic.yaml:/traefik_dynamic.yaml"
      - "./reverse-proxy/acme.json:/acme.json"

  pocketbase:
    image: "pocketbase:v1"
    container_name: "pocketbase"
    restart: "unless-stopped"
    ports:
      - "8000:8000"
    volumes:
      - "./backend/pb-data:/pb/pb_data"
