name: deploy_prod

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: configure_ssh
        env:
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod_key
          chmod 600 ~/.ssh/prod_key
          cat >>~/.ssh/config <<END
            Host prod
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/prod_key
              StrictHostKeyChecking no
          END
          
      - name: pull_changes
        run: ssh prod 'cd clever-cat && git pull'
      
      - name: deploy
        run: ssh prod 'cd clever-cat && docker compose down && docker compose up -d'
          
